# Generated by Django 4.2.1 on 2024-02-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_series', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
