# Generated by Django 4.2.1 on 2024-02-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_passport_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('appealType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.appealtype')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.government')),
            ],
        ),
    ]
