# Generated by Django 4.2.1 on 2024-02-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_appealtype_government_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
    ]
